# Generated by Django 5.2.5 on 2025-08-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='github_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
