# Generated by Django 5.2.4 on 2025-08-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='github_token',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='client',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
