# Generated by Django 5.2.4 on 2025-08-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_github_token_client_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='follwing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
