# Generated by Django 5.2.4 on 2025-08-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_followers_client_follwing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='follwing',
            new_name='following',
        ),
    ]
