# Generated by Django 5.2.5 on 2025-08-10 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo',
            old_name='url',
            new_name='html_url',
        ),
    ]
