# Generated by Django 5.2.4 on 2025-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
