# Generated by Django 5.2.4 on 2025-08-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_alter_repo_description_alter_repo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='commit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repo',
            name='open_issue_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repo',
            name='open_pr_count',
            field=models.IntegerField(default=0),
        ),
    ]
