# Generated by Django 5.2.5 on 2025-08-12 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_rename_url_repo_html_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='repo',
            name='github_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='repo',
            unique_together={('client', 'github_id')},
        ),
        migrations.AddIndex(
            model_name='repo',
            index=models.Index(fields=['client', 'github_id'], name='repo_repo_client__e87813_idx'),
        ),
    ]
