# Generated by Django 5.2.5 on 2025-08-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_repo_notifications_enabled_alter_repo_github_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='repo',
            name='repo_repo_client__e87813_idx',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='notifications_enabled',
        ),
        migrations.AlterField(
            model_name='repo',
            name='github_id',
            field=models.BigIntegerField(),
        ),
    ]
