# Generated by Django 5.2.5 on 2025-08-08 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_activities', to='repo.repo')),
            ],
        ),
    ]
