# Generated by Django 5.2.5 on 2025-08-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoActivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repoactivity',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
