# Generated by Django 5.2.4 on 2025-08-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoActivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repoactivity',
            name='github_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
