# Generated by Django 5.2.5 on 2025-08-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_repo_notifications_enabled_alter_repo_github_id_and_more'),
        ('repoActivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repoactivity',
            name='raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repoactivity',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='repoactivity',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='repoactivity',
            name='author',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='repoactivity',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='repoactivity',
            name='event_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='repoactivity',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='repoactivity',
            unique_together={('repo', 'event_id')},
        ),
        migrations.AddIndex(
            model_name='repoactivity',
            index=models.Index(fields=['repo', 'created_at'], name='repoActivit_repo_id_bccb9d_idx'),
        ),
        migrations.AddIndex(
            model_name='repoactivity',
            index=models.Index(fields=['type'], name='repoActivit_type_e41f5c_idx'),
        ),
    ]
