# Generated by Django 5.2.5 on 2025-08-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoActivity', '0002_repoactivity_raw_repoactivity_title_repoactivity_url_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='repoactivity',
            name='repoActivit_repo_id_bccb9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='repoactivity',
            name='repoActivit_type_e41f5c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='repoactivity',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='repoactivity',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repoactivity',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repoactivity',
            name='event_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='repoactivity',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='repoactivity',
            name='raw',
        ),
        migrations.RemoveField(
            model_name='repoactivity',
            name='title',
        ),
        migrations.RemoveField(
            model_name='repoactivity',
            name='url',
        ),
    ]
