# Generated by Django 5.2.5 on 2025-08-08 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commits_sms', models.BooleanField(default=False)),
                ('commits_email', models.BooleanField(default=False)),
                ('prs_sms', models.BooleanField(default=False)),
                ('prs_email', models.BooleanField(default=False)),
                ('issues_sms', models.BooleanField(default=False)),
                ('issues_email', models.BooleanField(default=False)),
                ('reviews_sms', models.BooleanField(default=False)),
                ('reviews_email', models.BooleanField(default=False)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='repo.repo')),
            ],
        ),
    ]
